version: '3.8'

services:
  ia-sw1-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    env_file:
      - .env
    volumes:
      # Solo montar el código fuente para desarrollo (opcional)
      - ./src:/app/src
    restart: unless-stopped
    container_name: ia-sw1-container
    networks:
      - ia-sw1-network

networks:
  ia-sw1-network:
    driver: bridge